// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/Editors/CodeEditor/index.vue')['default']
    DirectoryItem: typeof import('./src/components/DirectoryItem.vue')['default']
    DirectoryListing: typeof import('./src/components/DirectoryListing.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    Logo: typeof import('./src/components/shared/Logo.vue')['default']
    LogoSkeleton: typeof import('./src/components/shared/LogoSkeleton.vue')['default']
    ProgressView: typeof import('./src/components/shared/ProgressView.vue')['default']
    SideNavigationBar: typeof import('./src/components/SideNavigationBar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export { }
